//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SendPDFtoWebService.SendPdfToWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SendFaxGatewaySoap", Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgateway/1.0")]
    public partial class SendFaxGateway : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CaptureFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendFAXOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SendFaxGateway() {
            this.Url = global::SendPDFtoWebService.Properties.Settings.Default.SendPDFtoWebService_SendPdfToWebService_SendFaxGateway;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CaptureFileCompletedEventHandler CaptureFileCompleted;
        
        /// <remarks/>
        public event SendFAXCompletedEventHandler SendFAXCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
            "eway/1.0/CaptureFile", RequestNamespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
            "eway/1.0", ResponseNamespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
            "eway/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CaptureFile(string faxNumber, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] DocumentContent) {
            object[] results = this.Invoke("CaptureFile", new object[] {
                        faxNumber,
                        DocumentContent});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CaptureFileAsync(string faxNumber, byte[] DocumentContent) {
            this.CaptureFileAsync(faxNumber, DocumentContent, null);
        }
        
        /// <remarks/>
        public void CaptureFileAsync(string faxNumber, byte[] DocumentContent, object userState) {
            if ((this.CaptureFileOperationCompleted == null)) {
                this.CaptureFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCaptureFileOperationCompleted);
            }
            this.InvokeAsync("CaptureFile", new object[] {
                        faxNumber,
                        DocumentContent}, this.CaptureFileOperationCompleted, userState);
        }
        
        private void OnCaptureFileOperationCompleted(object arg) {
            if ((this.CaptureFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CaptureFileCompleted(this, new CaptureFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
            "eway/1.0/SendFAX", RequestNamespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
            "eway/1.0", ResponseNamespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
            "eway/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SendFAX(string faxNumber, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] DocumentContent) {
            object[] results = this.Invoke("SendFAX", new object[] {
                        faxNumber,
                        DocumentContent});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SendFAXAsync(string faxNumber, byte[] DocumentContent) {
            this.SendFAXAsync(faxNumber, DocumentContent, null);
        }
        
        /// <remarks/>
        public void SendFAXAsync(string faxNumber, byte[] DocumentContent, object userState) {
            if ((this.SendFAXOperationCompleted == null)) {
                this.SendFAXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFAXOperationCompleted);
            }
            this.InvokeAsync("SendFAX", new object[] {
                        faxNumber,
                        DocumentContent}, this.SendFAXOperationCompleted, userState);
        }
        
        private void OnSendFAXOperationCompleted(object arg) {
            if ((this.SendFAXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendFAXCompleted(this, new SendFAXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CaptureFileCompletedEventHandler(object sender, CaptureFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CaptureFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CaptureFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SendFAXCompletedEventHandler(object sender, SendFAXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendFAXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendFAXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591