//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0")]
[System.Xml.Serialization.XmlRootAttribute("SendOutboundFAX", Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0", IsNullable=false)]
public partial class SendOutboundFAXType {
    
    private string userNameField;
    
    private string passWordField;
    
    private string destinationField;
    
    private string priorityField;
    
    private string receiptField;
    
    private string senderField;
    
    private string faxRequestDateTimeField;
    
    private Document[] documentsField;
    
    /// <remarks/>
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    public string PassWord {
        get {
            return this.passWordField;
        }
        set {
            this.passWordField = value;
        }
    }
    
    /// <remarks/>
    public string Destination {
        get {
            return this.destinationField;
        }
        set {
            this.destinationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    public string Receipt {
        get {
            return this.receiptField;
        }
        set {
            this.receiptField = value;
        }
    }
    
    /// <remarks/>
    public string Sender {
        get {
            return this.senderField;
        }
        set {
            this.senderField = value;
        }
    }
    
    /// <remarks/>
    public string FaxRequestDateTime {
        get {
            return this.faxRequestDateTimeField;
        }
        set {
            this.faxRequestDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Document[] Documents {
        get {
            return this.documentsField;
        }
        set {
            this.documentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0")]
public partial class Document {
    
    private string seqNumberField;
    
    private string documentIdField;
    
    private DocumentType documentTypeField;
    
    private byte[] documentContentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string SeqNumber {
        get {
            return this.seqNumberField;
        }
        set {
            this.seqNumberField = value;
        }
    }
    
    /// <remarks/>
    public string DocumentId {
        get {
            return this.documentIdField;
        }
        set {
            this.documentIdField = value;
        }
    }
    
    /// <remarks/>
    public DocumentType DocumentType {
        get {
            return this.documentTypeField;
        }
        set {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] DocumentContent {
        get {
            return this.documentContentField;
        }
        set {
            this.documentContentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0")]
public enum DocumentType {
    
    /// <remarks/>
    PDF,
    
    /// <remarks/>
    xHTML,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("MS-DOC")]
    MSDOC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0")]
[System.Xml.Serialization.XmlRootAttribute("SendOutboundFAXAck", Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0", IsNullable=false)]
public partial class SendOutboundFAXAckType {
    
    private string transactionRefField;
    
    private OutcomeType outcomeField;
    
    private string errorCodeField;
    
    private string errorTextField;
    
    /// <remarks/>
    public string TransactionRef {
        get {
            return this.transactionRefField;
        }
        set {
            this.transactionRefField = value;
        }
    }
    
    /// <remarks/>
    public OutcomeType Outcome {
        get {
            return this.outcomeField;
        }
        set {
            this.outcomeField = value;
        }
    }
    
    /// <remarks/>
    public string ErrorCode {
        get {
            return this.errorCodeField;
        }
        set {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ErrorText {
        get {
            return this.errorTextField;
        }
        set {
            this.errorTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0")]
public enum OutcomeType {
    
    /// <remarks/>
    Success,
    
    /// <remarks/>
    Failure,
    
    /// <remarks/>
    Acknowledge,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0")]
[System.Xml.Serialization.XmlRootAttribute("CheckFAXStatus", Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0", IsNullable=false)]
public partial class CheckFAXStatusType {
    
    private string userNameField;
    
    private string passWordField;
    
    private string transactionRefField;
    
    /// <remarks/>
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    public string PassWord {
        get {
            return this.passWordField;
        }
        set {
            this.passWordField = value;
        }
    }
    
    /// <remarks/>
    public string TransactionRef {
        get {
            return this.transactionRefField;
        }
        set {
            this.transactionRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0")]
[System.Xml.Serialization.XmlRootAttribute("SendOutboundFAXResult", Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0", IsNullable=false)]
public partial class SendOutboundFAXResultType {
    
    private string transactionRefField;
    
    private StatusType statusField;
    
    private OutcomeType outcomeField;
    
    private bool outcomeFieldSpecified;
    
    private string errorCodeField;
    
    private string errorTextField;
    
    private string faxSendDateTimeField;
    
    /// <remarks/>
    public string TransactionRef {
        get {
            return this.transactionRefField;
        }
        set {
            this.transactionRefField = value;
        }
    }
    
    /// <remarks/>
    public StatusType Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public OutcomeType Outcome {
        get {
            return this.outcomeField;
        }
        set {
            this.outcomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OutcomeSpecified {
        get {
            return this.outcomeFieldSpecified;
        }
        set {
            this.outcomeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ErrorCode {
        get {
            return this.errorCodeField;
        }
        set {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ErrorText {
        get {
            return this.errorTextField;
        }
        set {
            this.errorTextField = value;
        }
    }
    
    /// <remarks/>
    public string FaxSendDateTime {
        get {
            return this.faxSendDateTimeField;
        }
        set {
            this.faxSendDateTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0")]
public enum StatusType {
    
    /// <remarks/>
    Complete,
    
    /// <remarks/>
    Incomplete,
}
